language: java
jdk:
  - oraclejdk8
script:
  - mvn install -DskipTests=true
  - mvn test
  - mvn install -DskipTests=true -Pmockito2
  - mvn test -Pmockito2
  - mvn install -DskipTests=true -Pacceptance -Pmockito
  - mvn test -Pacceptance -Pmockito

